---
services:
  satisfactory:
    image: indifferentbroccoli/satisfactory-server-docker
    restart: unless-stopped
    container_name: satisfactory
    stop_grace_period: 30s
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - .env.example
    volumes:
      - ./satisfactory/server-files:/satisfactory
      - ./satisfactory/server-data:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
