---
name: Security
on:
  pull_request: null
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
jobs:
  container-scanning:
    name: Container - Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          load: true
          tags: security
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: security
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
